name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # ← mainにpushされたとき
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install JS dependencies
        run: yarn install

      - name: Build JavaScript
        run: yarn build

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ikuji_app-web:${{ github.ref_name }} .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ikuji_app-web:${{ github.ref_name }}bun